export const events = {
    EMPTY_USER: 'EMPTY_USER',
    ERROR_USER: 'ERROR_USER',
    SUCCESS_USER: 'SUCCESS_USER',
    ERROR_REPOSITORY: 'ERROR_REPOSITORY',
    SUCCESS_REPOSITORY: 'SUCCESS_REPOSITORY',
};